language: python
sudo: true
python:
  - "3.7.3"
cache: pip
install:
  - pip3 install -r requirements.txt
  - nvm install 10
  - npm install -g jscpd@3.2.1
jobs:
  include:
    
    - stage: "Tests & Coverage"
      name: "Unit and functional test with coverage"
      script:
        - pytest test --cov-config=.coveragerc --cov=guardrails
        - coverage report --fail-under=90 #Coverage should be above 90%
      after_success: codecov
